### ISSUE TITLE
Расположение border и border-radius

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#1]
Значения border и border-radius правильнее было бы выводить после background в разделе эффекты https://skr.sh/sOCl5H7Pqaz

**Comment by maxdenaro** [comment]
Сомневаюсь в этом, ведь бордер как раз входит в блочную модель. Ну а бордер-радиус под самим бордером - очень удобно.

**Comment by Remzi17** [comment]
вот парочка статей из популярных сайтов по запросу "Порядок свойств css"

- https://netology-university.bitbucket.io/codestyle/css/
- https://webformyself.com/eshhe-raz-poryadok-svojstv-css/

**Comment by maxdenaro** [comment]
Но это лишь их субъективное представление этой темы. Могу сделать статью на тему, она через месяц тоже в топах интернета будет. Это ж не значит, что я единственная истина :)

А вот то, что бордер относится к блочной модели - неоспоримый факт.

Можно даже проще сделать. Если свойство реально меняет только внешний вид - относим к эффектам. Но бордер меняет и размер элемента, потому и находится там, где находится.
