### ISSUE TITLE
Точка с запятой в svg

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#10]
В стилях для svg не учитывается выбранный препроцессор. У меня выбран sass, но **;** все равно есть 
<img width="530" alt="image" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/81004282/0d74708e-4791-435d-a512-ef68400120e7">

**Comment by maxdenaro** [comment]
Поправлено, плагин обновится сегодня-завтра.
