### ISSUE TITLE
Auto-layout не работает

### ISSUE THREAD

**Issue by Counserf** [maxdenaro/inspect-styles-feedback#11]
![qlVnGpC 1](https://github.com/maxdenaro/inspect-styles-feedback/assets/34280229/d82b583f-fa9a-41a6-a0c7-403e92ea23d8)
Если выбрать расположение элемента wrap (справа, там также есть горизонтальное и вертикальное расположение), то будет показывать стили в формате svg

**Comment by maxdenaro** [comment]
Здравствуйте. А что должно быть? Это фрейм с квадратами внутри, как я вижу. Потому и выдаёт свг, это и есть свг

**Comment by Counserf** [comment]
Это auto-layout, соответственно, если включён флексбокс, то должны быть стили автолэйаута

**Comment by Counserf** [comment]
**конкретно у этого элемента стили выглядят так**
/* [box] */

/* Auto layout */
display: flex;
flex-direction: row;
flex-wrap: wrap;
align-items: flex-start;
align-content: flex-start;
padding: 16px;
gap: 21px 26px;

position: absolute;
width: 125px;
height: 180px;
left: calc(50% - 125px/2 - 41.5px);
top: calc(50% - 180px/2);

background: #0096FF;
border-radius: 16px;

**Comment by maxdenaro** [comment]
Все верно. Будь там контент, а не просто квадраты, плагин бы выдал флекс. А поскольку его там нет - смысла выдавать флекс нет, это больше похоже на свг-контент.

![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/25548841/432f55f6-27fb-4fa0-993e-2db455890b2a)

**Comment by Counserf** [comment]
Окей, закрываю
