### ISSUE TITLE
Interaction и Animations

### ISSUE THREAD

**Issue by Counserf** [maxdenaro/inspect-styles-feedback#12]
В процессе работы многие работают с интерактивностью.
Если есть возможность, добавить информацию об этом в Isnpect Styles

![OJJgLUE 1](https://github.com/maxdenaro/inspect-styles-feedback/assets/34280229/5527c549-01bc-48c8-90bf-09092e713223)

Если нажимать на этот блок, то копируется код:
```css
// While hovering
// Change to: "Filled, hovered, Show Icon=False";
// Animate: Smart animate;
animation-timing-function: cubic-bezier(0.2, 0, 0, 1);
animation-duration: 200ms;

// While pressing
// Change to: "Filled, pressed, Show Icon=False";
// Animate: Smart animate;
animation-timing-function: cubic-bezier(0.2, 0, 0, 1);
animation-duration: 200ms;
```

**Comment by Counserf** [comment]
Конкретно свойство этого блока работает с компонентом, но также существуют переходы с страницы на страницу, открытие drawer-ов и другие интерактивности

**Comment by maxdenaro** [comment]
Добрый вечер! А можно ссылочку на фигму с подобным блоком? посмотрю, есть ли вообще что-то в апи

**Comment by maxdenaro** [comment]
Нет ответа, закрываю ишью.
