### ISSUE TITLE
Inspect Styles на Макбук не работает корректно

### ISSUE THREAD

**Issue by Anastasiia-Bekirova** [maxdenaro/inspect-styles-feedback#13]
плагин не показивает параметри виделенного текста, такие как: Line-height, Font-size, Font-weight, etc
<img width="1728" alt="Знімок екрана 2024-04-14 о 11 30 35" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/165383483/83db2495-62ab-4ca4-850d-d893cdb3e8e6">
<img width="1728" alt="Знімок екрана 2024-04-14 о 11 31 07" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/165383483/aaa54231-6eef-4637-b990-14154091ba1f">
<img width="1728" alt="Знімок екрана 2024-04-14 о 11 31 15" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/165383483/4ce68864-96e3-4787-9f85-7c5ec36cf428">

**Comment by maxdenaro** [comment]
Здравствуйте. В другом браузере или десктоп-приложении пробовали?

Про сафари мне писало несколько человек, но лично у меня в сафари все отлично.

**Comment by Anastasiia-Bekirova** [comment]
Здравствуйте. Скачала десктопную версию - и свершилось чудо! Теперь все отображается. Спасибо огромное!

**Comment by maxdenaro** [comment]
Рад помочь)
