### ISSUE TITLE
Не подтягивается max-width и скорее всего остальные min/max

### ISSUE THREAD

**Issue by aatuzhilkin** [maxdenaro/inspect-styles-feedback#14]
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/167068210/4fa56642-8048-42ee-8545-e39e59399bf2)

**Comment by maxdenaro** [comment]
О, теперь в фигму и такое добавили) Не видел даже.
Посмотрю, есть ли доступ в апи к такому.

Ну и вообще всеми ишью займусь на след. неделе

**Comment by maxdenaro** [comment]
Фича реализована, появится сегодня-завтра.
