### ISSUE TITLE
Отображение градиента, прозрачность в градиенте

### ISSUE THREAD

**Issue by Foxquiz** [maxdenaro/inspect-styles-feedback#15]
В linear-gradient не учитывается прозрачность. 
На данный момент на одном из [макетов](https://www.figma.com/file/y5YuwAt3Y8MOdkemQOOpG4/Lagoona-(Copy)?type=design&node-id=370726-57&mode=design&t=x4XBiRczX7aYQK0d-0) перестал отображаться градиент.
 ![Screenshot](https://github.com/maxdenaro/inspect-styles-feedback/assets/70839661/baa69925-8ccf-4f67-ab93-5ac8249c6dd7)

Ранее выводилось следующее:
` background: linear-gradient(90deg, #304059 0%, #354153 66.67%) `
 вместо 
` background: linear-gradient(90deg, rgba(48, 64, 89, 0.84) 0%, rgba(53, 65, 83, 0.00) 66.67%) `

Ранее отображалось:
![Screenshot-2](https://github.com/maxdenaro/inspect-styles-feedback/assets/70839661/5d1e788d-6d2f-497f-b4be-4faf15919d39)

Отображение в девмод:
![Screenshot-3](https://github.com/maxdenaro/inspect-styles-feedback/assets/70839661/785fb921-4619-4c62-a397-fd0a583112c1)

Возможно исправить?

**Comment by maxdenaro** [comment]
Добрый день! В соседнем ишью уже отписался. Это, похоже, проблема со стороны Фигмы. В API просто не отображаются точки градиента. С последним обновлением сломали именно данные из API. Поэтому ждем, как только пофиксят - буду смотреть насчет прозрачности.

**Comment by maxdenaro** [comment]
Добрый вечер. Посмотрел сейчас - проблема ушла. Допонительно пофиксил прозрачность, теперь все работает как надо. Изменения залил
