### ISSUE TITLE
Отображение стилей текста

### ISSUE THREAD

**Issue by RussianBoy64** [maxdenaro/inspect-styles-feedback#16]
При выборе текста перестали отображаться стили
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/85865879/494266a2-b1f0-4f89-832e-d5f88e14f821)

![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/85865879/f487c739-25a6-422b-8ad0-8f3af615c513)

Возможно исправить?

**Comment by maxdenaro** [comment]
Добрый день.
Нужен макет, чтобы проверить ошибку.

**Comment by maxdenaro** [comment]
Если сможете скинуть макет в новом ишью - я посмотрю. К сожалению, пока предположить в чем проблема невозможно.
