### ISSUE TITLE
Не отображаются данные градиентной заливки

### ISSUE THREAD

**Issue by D-double** [maxdenaro/inspect-styles-feedback#17]
При клике не элемент с градиентной заливной данные отображаются только вот так
background: linear-gradient(90deg, );
Нет отображения значений цветов, прозрачности, положения.

**Comment by maxdenaro** [comment]
Макет не скинули.

**Comment by D-double** [comment]
Так у меня во всех макетах так. Вот могу ссылку один отправить.

https://www.figma.com/file/UBPyGReA2HDiif935NU7Ap/Vue-%D1%81inemas?node-id=0%3A1&t=mqxZ0xmlLyvaTdp1-1


сб, 27 апр. 2024 г., 23:24 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Я понимаю, но просто у меня такого нет) поэтому нужен макет.
Спасибо, буду смотреть в выходные

**Comment by maxdenaro** [comment]
Посмотрел, поискал информацию.
Похоже, это ошибка со стороны Фигмы.
После недавнего обновления, если создавать градиент с нуля - плагин его покажет. А все то, что было создано до обновления - сломалось.

https://forum.figma.com/t/plugin-api-gradientstops-array-empty-for-objects-created-before-v1-92-update/70644

Тут как раз пишут, что тоже столкнулись с таким. Поэтому ждем фикс.
А пока добавлю оповещение в плагин для таких ситуаций.

**Comment by D-double** [comment]
Я могу даже на видео записать проблему, но у тебя на сервере ограничение на
размер файлов, поэтому оно не дойдёт.)

сб, 27 апр. 2024 г., 23:34 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Я уже все увидел) Но тут я бессилен, проблема со стороны апишки. Ждем, надеюсь разработчики фигмы это пофиксят

**Comment by D-double** [comment]
Ок. Жаль, придётся пока переходить на pixso

сб, 27 апр. 2024 г., 23:53 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Можно же во вкладке properties посмотреть :) Там все работает, сломалось именно API для плагинов.

**Comment by D-double** [comment]
Если я правильно понял, то ты предлагаешь посмотреть значения градиента и
ручками вписать цвета и прозрачность.) Но в моем случае это не подойдёт,
так как я работаю преподавателем и это нужно вписывать студентам, а для них
это прям очень долго и куча ошибок при написании, поэтому их легче
пересадить на другое приложение где все будет быстро, бесплатно и удобно. :)

сб, 27 апр. 2024 г., 23:58 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Не-не, извращениями заниматься не нужно :)
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/25548841/d3987e90-8c6a-463a-8a22-c6ff18939456)
Можно навести, будет copy) И все

**Comment by D-double** [comment]
Погоди у тебя фигма случайно не платная подписка и ты случайно не в режиме
разработчика это показываешь? :) Потому что у меня бесплатный вариант и
такой вкладки у меня нет.

вс, 28 апр. 2024 г., 00:15 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Нет-нет, это обычная панелька в бесплатной фигме, которая доступна всем.
Но наверное она доступна только в макетах, которые БЕЗ доступа к редактирования.

**Comment by D-double** [comment]
Да, только в режиме просмотра, в режиме редактирования такого нет. Видимо
придётся так выходить из ситуации. Спасибо, за помощь.
Но как ни крути, потихоньку вынуждают переходить на другие приложения.
Иначе приходится выдумывать танцы с бубнами. :)

вс, 28 апр. 2024 г., 00:22 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Да баги бывают у всех)) пофиксят, я думаю, и все. Слава богу, градиенты в целом не сильно частая фишка в макетах

**Comment by D-double** [comment]
Ооо, не скажи, у нас что ни макет то градиент. А этот так весь на грдиентах
и еще для разных тем операционной системы. Поэтому надеюсь что скоро
исправят и можно будет не беспокоиться.
Спасибо, за помощь. Я спать. :)

вс, 28 апр. 2024 г., 00:36 Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Проверил сейчас еще раз макеты - проблема ушла. Если вдруг будет еще что-то - создавай новое ишью)

**Comment by D-double** [comment]
Да, спасибо, проблема ушла, теперь все работает.

вт, 30 апр. 2024 г., 23:11 Maksim Vasyanovich ***@***.***>:
