### ISSUE TITLE
Неправильно отображение комментария в css при включенном параметре  Add line-height "px" comment

### ISSUE THREAD

**Issue by DenisMalv** [maxdenaro/inspect-styles-feedback#18]
Сейчас отображается комментарий как // тоесть как в коде js, при вставке его в файл css бьет ошибку. 

<img width="347" alt="Monosnap Design (Copy) – Figma 2024-08-01 11-55-01" src="https://github.com/user-attachments/assets/f4f611da-d266-48d3-b0dc-49dd904909c0">

Некоторое время назад было все ок коментарий был как в css формате. 

<img width="344" alt="Monosnap Design (Copy) – Figma 2024-08-01 12-00-40" src="https://github.com/user-attachments/assets/e1b134b9-7dc8-4e1b-9272-2a01be529a07">

Сделайте пожалуйте как било раньше что бы при вставке в css не было ошибок 🙏

ссылка на макет https://www.figma.com/design/jHwqOlOy70YCQzI4dK8ATG/Design-(Copy)?node-id=0-1&t=hV2Ms1aKXeeEL7cU-1

**Comment by maxdenaro** [comment]
Привет! Тут скорее не из js комментарий, а из sass) Сейчас плагин обновил, должно быть окей.

**Comment by DenisMalv** [comment]
Супер! Спасибо за такой быстрый ответ 🙌🙏

**Comment by maxdenaro** [comment]
Отлично) закрываю тогда)
