### ISSUE TITLE
Не валидное названия переменных цвета в :root а также в боксах свойств

### ISSUE THREAD

**Issue by Serg-P** [maxdenaro/inspect-styles-feedback#2]
при генерации переменных нужно убрать символ решетки 
также убрать из свойств стилей 

https://prnt.sc/T3HY5DFnmW-k
https://prnt.sc/JuxPXsiwF9nI
https://prnt.sc/0XchMDkbl7IU

**Comment by maxdenaro** [comment]
Добрый день!

Странные дизайнеры, которые так называют переменные :) 
Взял в работу, постараюсь сегодня обновить плагин.

**Comment by maxdenaro** [comment]
Обновление опубликовано. Спасибо за выявленную ошибку)
