### ISSUE TITLE
Можно ли убрать переменные ? 

### ISSUE THREAD

**Issue by Breeze8** [maxdenaro/inspect-styles-feedback#21]
Добрый вечер. Подскажите, плагин тянет все переменные которые задал дизайнер, нет возможности их отключить как-то, чтобы туда подтягивался именно стиль вместо переменной ? 

Пример border: 1px solid $border-onwhite-20% ( это так показывает плагин )

**Comment by maxdenaro** [comment]
Здравствуйте. Конечно, в настройках есть соответствующая опция)
А можете прислать макет, или хотя бы кусочек, где такое название переменной? Сделаю хотя бы валидное название
