### ISSUE TITLE
Отображение градиента

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#22]
1. Не совсем правильно выводится радиальный градиент. Ссылка на макет https://www.figma.com/design/h3iFoAQziHzsbA7GQhsmmU/Untitled?node-id=3089-8685&t=9HYFJADRtXAF9Pom-1

В фигме появилась кнопка, которая выдаёт готовый background 
<img width="119" alt="image" src="https://github.com/user-attachments/assets/5d0d5cfb-d51c-425e-8918-3553d878fc2b">

и он отличается от кода, выводимого плагином. Вместо 
background: radial-gradient(50% 50% at 50% 50%, rgba(215, 201, 151, 0.12) 0%, rgba(215, 202, 152, 0) 100%);
 
выводится 
background: radial-gradient(50% 50% at 50% 50%, rgb(215, 201, 151) 0%, rgb(215, 202, 152) 100%)

2. Если бы увеличили размер шрифта в интерфейсе на несколько пикселей - было бы лучше. А то на больших мониторах мелковато выглядит. Даже если растянуть окно плагина.

**Comment by maxdenaro** [comment]
Добрый день. Да, с градиентами у плагина есть проблемы. Нигде нет четкой инструкции, как правильно преобразовывать данные из фигмы в реальный градиент.

Проблему я исправил, но все же рекомендую к фигме тоже обращаться в вопросах градиента, сверяться.

Насчет шрифта - пока глобально не придет запрос от большого количества человек на это, исправить не могу. Всем не угодишь(
