### ISSUE TITLE
Размер шрифта в интерфейсе

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#3]
На большом мониторе размер шрифта кода выглядит мелковато. Было бы удобно, если в настройках была опция выбора размера шрифта интерфейса 

<img width="954" alt="image" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/81004282/c31c209b-eb5e-43c0-b820-5e66f298164d">

**Comment by maxdenaro** [comment]
Добрый вечер! Для увеличения шрифта нужно растянуть окно плагина, шрифт увеличится автоматически.

**Comment by Remzi17** [comment]
@maxdenaro Добрый день. Можете на 2-3 пикслея увеличить шрифт в растянутой версии. Свободного места достаточно. А то всё равно  выглядит мелковато
