### ISSUE TITLE
Прозрачность в градиенте

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#4]
В linear-gradient не учитывается прозрачность. В этом примере выводит **_background: linear-gradient(270deg, #9c2c34 7.54%, #75160f 94.69%)_**  вместо  **_background: linear-gradient(270deg, rgba(#9c2c34, .12) 7.54%, rgba(#75160f, .12) 94.69%)_**  Можно это исправить? Проблема не только в одном месте, в разных макетах проверял

<img width="795" alt="image" src="https://github.com/maxdenaro/inspect-styles-feedback/assets/81004282/61083236-c8ba-4309-9708-685fa1560033">

**Comment by maxdenaro** [comment]
Добрый день!

Скиньте пожалуйста ссылку на макет (можно вынести туда просто этот элемент с текстом), будет удобнее тестировать.

По срокам пока сказать не могу, но займусь.

**Comment by Remzi17** [comment]
https://www.figma.com/file/id7SzrxIOrEuGRHMZd53vI/Untitled?type=design&node-id=0%3A1&mode=dev&t=VubGQJUV0mhZaEmc-1

**Comment by maxdenaro** [comment]
Градиент исправлен) спасибо за выявленный баг
