### ISSUE TITLE
Если к переменной цвета присвоить цвет другой переменной, то плагин сломается

### ISSUE THREAD

**Issue by Counserf** [maxdenaro/inspect-styles-feedback#5]
Если к переменной цвета присвоить цвет другой переменной, то плагин сломается

**Comment by maxdenaro** [comment]
Все верно. Плагин после этого надо перезапустить

**Comment by Counserf** [comment]
Он перестаёт работать, даже если перезапустить

**Comment by Counserf** [comment]
Скрин что имею ввиду
https://i.imgur.com/72RLTAW.png

**Comment by maxdenaro** [comment]
Нужны подробности. Покажите, что делаете, и что происходит

**Comment by maxdenaro** [comment]
А, вот оно что.
Да, плагин с таким поведением не работает, и честно говоря не понимаю зачем так делать)

**Comment by Counserf** [comment]
Дизайнеры так делают для того, чтобы не запоминать какие переменные использовать в элементах интерфейса.
Они создают переменные для каждого цвета в компоненте (например у кнопки) и называют его соответственно.
Вот пример:
https://i.imgur.com/LLU8fKT.png

Так сказать, "чтобы не перепутать" цвет при присвоении переменных к элементу

**Comment by maxdenaro** [comment]
Первый раз такое вижу.
Посмотрю, что можно сделать

**Comment by Counserf** [comment]
Вот как пример. Учитывая, что при создании проектов люди могут интегрировать переменные в свои проекты им легче править цвета всего проекта в одной мастер-группе переменных чем абсолютно во всех
https://www.figma.com/community/file/1314836077957823617/atomaro-pro-design-system

**Comment by maxdenaro** [comment]
А какой результат вы ожидаете? 
Если в переменных написано так:
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/25548841/126739ea-0062-41f5-ae0e-63afd478aceb)
то плагин должен выдать

```
--white: #fff;
--text-color: var(--white)
```
?

**Comment by maxdenaro** [comment]
по-прежнему считаю бесполезной затеей так делать, лишнее усложнение и макета, и верстки :)

**Comment by maxdenaro** [comment]
Пока что убрал ошибку, обновил плагин.

**Comment by Counserf** [comment]
вообще что-то типа того наверное, хотя вариант с использованием исходной переменной мне нравится)

**Comment by maxdenaro** [comment]
Фича реализована, появится сегодня-завтра.
