### ISSUE TITLE
Отображение margin, border, padding в графическом виде с возможностью копирования css при нажатии на блок

### ISSUE THREAD

**Issue by Counserf** [maxdenaro/inspect-styles-feedback#7]
Как в dev mode
https://i.imgur.com/AqszvQ7.png

**Comment by maxdenaro** [comment]
А зачем это? бесполезная штука как в девтулс, так и в дев моде.

**Comment by Counserf** [comment]
Визуально облегчает восприятие для разработчиков

**Comment by Counserf** [comment]
Сразу графически показывает к чему применяются свойства - условно к правому углу - скругление

**Comment by maxdenaro** [comment]
Сомнительная штука. Не вижу пока смысла тратить на это время.
