### ISSUE TITLE
Копирование при выделении

### ISSUE THREAD

**Issue by Remzi17** [maxdenaro/inspect-styles-feedback#8]
Было бы удобно, если бы выделенный текст после окончания выделения автоматически помещался в буфер обмена. Например, https://skr.sh/sOWOqCkJkww если я три раза нажал на строку с color и она автоматически выделилась и в конце сразу скопировалась.  Такое в avocode раньше было, если помните) 

Думаю реализовать это несложно

**Comment by maxdenaro** [comment]
Добавил данный функционал.
