### ISSUE TITLE
Wrong colors and elements position.

### ISSUE THREAD

**Issue by AndrewBBx** [maxdenaro/inspect-styles-feedback#9]
I use a Figma web version in the dark mode. The text color is black on the dark background, and the elements' positions are wrong. I made the size of the style window maximum available, but it didn't help.
Browser -  opera last version
OS - Ubuntu 18.04
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/136701535/c54ea814-fa90-4b2d-a4ab-5abdad64ef08)

**Comment by maxdenaro** [comment]
Hi! Does this always happen, or only when the plugin is loaded?

Have you tried another browser or desktop application?

**Comment by AndrewBBx** [comment]
It happens where the plugin starts, after ~5 min positions, and colors start to look normal.
I've tried a Chrome browser (same issue), native app didn't try.

**Comment by maxdenaro** [comment]
This means that the plugin is loading all this time. Do you have many layers\frames in your layout?
If possible, drop the link to the layout, please.

**Comment by AndrewBBx** [comment]
Ah, okay, thanks.
Not too much. I can't share a link, but I have only 3 components there.

Is this plugin good for a big project? 
![image](https://github.com/maxdenaro/inspect-styles-feedback/assets/136701535/3e8bb763-378c-4dde-8d82-757fb8d7e300)
(that's all that I have in Figma)

**Comment by maxdenaro** [comment]
This is strange. I am currently working on a website with about 10 layouts on one page - and everything is fine, it loads instantly. That's why I asked for a link, it would be necessary to test your components, perhaps something in them makes the plugin hang.

Maybe you can make similar components and drop a link to it?
